#!/usr/bin/env python3
"""MP-003: reconcile open checkboxes in NEXT_100_STEPS.md / ROADMAP.md against the code, with reproducible evidence.

For each open item it searches the sources (src/, scripts, workflows, docs) for the symbols that would exist if the
item were built, and the git history for the commit that introduced the first hit. It only REPORTS. A hit is evidence
to go and read, not proof: a maintainer (or reviewer) decides what to tick, so a keyword collision can never mark
unbuilt work done. Output: reports/doc_reconcile.md.   Usage: python tools/doc_reconcile.py
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCAN = [ROOT / "src", ROOT / "scripts", ROOT / ".github", ROOT / "pom.xml", ROOT / "INSTALLER.md"]
SUFFIX = {".java", ".py", ".sh", ".yml", ".yaml", ".xml", ".md", ".json", ".bat", ".ps1", ".vert", ".frag"}

# item label -> regexes that should hit in the source IF the item is built
EVIDENCE = {
    "NEXT_100 #91 open-issue crystals": [r"listIssues", r"TODO crystal|renderCrystals"],
    "NEXT_100 #92 issue verdicts (quorum votes, comment add-only)": [r"issue.?verdict", r"createIssueComment|postIssueComment|addComment"],
    "NEXT_100 #93 repo health rollup": [r"health.?rollup|repoHealth|HealthRollup"],
    "NEXT_100 #94 nightly repo sweep": [r"nightly.?sweep|RepoSweep"],
    "NEXT_100 #95 commit engravings": [r"renderCommitEngravings", r"commit.?engraving"],
    "NEXT_100 #96 push gate (quorum APPROVED on exact diff)": [r"push.?gate|PushGate"],
    "NEXT_100 #97 agent/<step> preview branches": [r"agent/<step>|agent/\" \+|previewBranch"],
    "NEXT_100 #98 weekly self-report": [r"weekly.?(self.?)?report|WeeklyReport"],
    "NEXT_100 #99 compute tax": [r"compute.?tax|computeTax"],
    "NEXT_100 #100 idle decay": [r"idle.?decay|skillDecay"],
    "NEXT_100 #101 energy budget": [r"energy.?budget|EnergyBudget"],
    "NEXT_100 #102 cost telemetry": [r"cost.?telemetry|CostTelemetry"],
    "NEXT_100 #103 FLASH model lane": [r"\bFLASH\b"],
    "NEXT_100 #104 quota firewall / burst client": [r"quota.?firewall|burst.?client|BurstClient"],
    "NEXT_100 #105 quota ledger": [r"quota.?ledger|QuotaLedger"],
    "NEXT_100 #106 dedupe sentinel": [r"dedupe.?sentinel|DedupeSentinel"],
    "NEXT_100 #107 doc-drift sentinel": [r"doc.?drift|DocDrift"],
    "NEXT_100 #108 multiplayer WebSocket contract": [r"WebSocket"],
    "NEXT_100 #109 installer v2 (jpackage msi)": [r"jpackage"],
    "NEXT_100 #110 installer clean-path QA": [r"clean.?path"],
    "ROADMAP Windows installer / jpackage": [r"jpackage|Inno Setup"],
    "ROADMAP CI/CD": [r"runs-on:"],
    "ROADMAP test suite": [r"selftest|RESULT:"],
    "ROADMAP UDP multiplayer": [r"DatagramSocket|DatagramChannel"],
    "ROADMAP embedded scripting engine": [r"GraalVM|ScriptEngine|org\.graalvm"],
    "ROADMAP gamepad support": [r"glfwJoystick|GLFW_JOYSTICK|glfwGetGamepad"],
    "ROADMAP VR / OpenXR": [r"OpenXR|org\.lwjgl\.openxr"],
    "ROADMAP auto-updater (Releases API)": [r"releases/latest|LiveUpdateManager"],
    "ROADMAP weather sync": [r"WeatherBlock|weather.?sync|open-meteo"],
    "ROADMAP day/night cycle": [r"skyPhase|drawSkyDome"],
    "ROADMAP rebindable keys / invert Y": [r"invertY|rebind"],
    "ROADMAP safe / AES-256": [r"AES|Cipher\.getInstance"],
    "ROADMAP hover tooltip on books": [r"renderBookTooltip"],
    "ROADMAP pull images from repos to posters": [r"renderRoomPoster|image.?source|raw\.githubusercontent"],
    "ROADMAP cat / Curie": [r"Calico|\bcat door|Curie"],
    "ROADMAP never-code-twice DB": [r"never.?twice|NeverTwice"],
    "ROADMAP Tree of Knowledge webcrawl": [r"webcrawl|Squigly"],
}


def files():
    """Files (function)."""
    for base in SCAN:
        if base.is_file():
            yield base
        elif base.is_dir():
            for p in base.rglob("*"):
                if p.is_file() and p.suffix in SUFFIX and ".worktrees" not in p.parts and "target" not in p.parts:
                    yield p


def first_commit(pattern, rel):
    """First commit.

    Args: pattern, rel.
    """
    try:
        r = subprocess.run(["git", "-C", str(ROOT), "log", "--format=%h %s", "-G", pattern, "--", rel],
                           capture_output=True, text=True, timeout=60, stdin=subprocess.DEVNULL)
        lines = [ln for ln in r.stdout.splitlines() if ln.strip()]
        return lines[-1][:90] if lines else ""
    except (subprocess.TimeoutExpired, OSError):
        return ""


def main():
    """Main (function)."""
    cache = {p: p.read_text(encoding="utf-8", errors="replace").splitlines() for p in files()}
    out = ["# Doc reconcile (MP-003)", "",
           "Generated by `tools/doc_reconcile.py`. Hits are EVIDENCE TO READ, not proof; nothing is ticked automatically.", "",
           "| Item | Evidence | First commit touching it |", "|---|---|---|"]
    summary = []
    for label, pats in EVIDENCE.items():
        hits = []
        for pat in pats:
            rx = re.compile(pat, re.I)
            for p, lines in cache.items():
                for i, ln in enumerate(lines, 1):
                    if rx.search(ln):
                        hits.append((pat, p.relative_to(ROOT).as_posix(), i))
                        break
                if len(hits) >= 3:
                    break
        ev = "; ".join(f"{f}:{n}" for _, f, n in hits[:3]) or "**none found**"
        commit = first_commit(hits[0][0], hits[0][1]) if hits else ""
        out.append(f"| {label} | {ev} | {commit} |")
        summary.append((label, bool(hits)))
    (ROOT / "reports").mkdir(exist_ok=True)
    (ROOT / "reports" / "doc_reconcile.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    with_ev = [s for s, ok in summary if ok]
    print(f"{len(with_ev)} of {len(summary)} open items have code evidence to review; report: reports/doc_reconcile.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
